title: Problem Solving using Python
description: >-
  Problem Solving using python course focuses on developing you with core python
  skills starting from the introduction to object oriented, data structures,
  algorithms with python that will help you to solve problems competitive and
  scenario based problems.
template:
  repo: problem-solving-using-python-template
  name: problem-solving-using-python
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
